//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
	public partial class Demo2Entities : DbContext
	{

		private static Demo2Entities _context;
		public Demo2Entities()
            : base("name=Demo2Entities")
        {
        }

        public static Demo2Entities GetContext()
        {
            if (_context == null)
                _context = new Demo2Entities();
            return _context;
        }

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Дополнительные_услуги_> C_Дополнительные_услуги_ { get; set; }
        public virtual DbSet<Заявки> Заявки { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Пользователь> Пользователь { get; set; }
        public virtual DbSet<Помещение> Помещение { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<C_Тип_помещения_> C_Тип_помещения_ { get; set; }
        public virtual DbSet<C_Тип_уборки_> C_Тип_уборки_ { get; set; }
        public virtual DbSet<C_Услуги_в_зявке_> C_Услуги_в_зявке_ { get; set; }
    }
}
