//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявки()
        {
            this.C_Услуги_в_зявке_ = new HashSet<C_Услуги_в_зявке_>();
        }
    
        public int Id { get; set; }
        public int Помещение { get; set; }
        public int Клиент { get; set; }
        public int Тип_уборки { get; set; }
        public Nullable<System.DateTime> Дата_исполнения { get; set; }
        public Nullable<int> Исполнитель { get; set; }
    
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Клиент Клиент1 { get; set; }
        public virtual Помещение Помещение1 { get; set; }
        public virtual C_Тип_уборки_ C_Тип_уборки_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Услуги_в_зявке_> C_Услуги_в_зявке_ { get; set; }
    }
}
