//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Помещение
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Помещение()
        {
            this.Заявки = new HashSet<Заявки>();
        }
    
        public int Id { get; set; }
        public string Адрес { get; set; }
        public Nullable<double> Площадь { get; set; }
        public int Тип_помещения { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявки> Заявки { get; set; }
        public virtual C_Тип_помещения_ C_Тип_помещения_ { get; set; }
    }
}
